### PR TITLE
fix(package): revert next-mdx-remote to v3

### PR DESCRIPTION
**Pull request by mateonunez**

### CODE REVIEW

**Comment by GuidoPenta** [comment]
MATEOOOOOOOOOOOOOOOOOOOOOOOOOOOO
DON'T BREAK EVERYTHING MATEOOOOOOOOOOOOOOOOOOO

**Comment by KristianLentino99** [comment]
Hai fatto Tinder Premium?

**Comment by MarcoDoC** [comment]
MATEOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by mateonunez** [comment]
NON VA UNA MINCHIA.

**Pull request merged**
